name: PR Conflict Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-merge-conflict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Attempt to merge with base
        id: merge_check
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout -b merge-check
          if git merge origin/${{ github.event.pull_request.base.ref }} --no-commit --no-ff; then
            echo "merge_conflict=false" >> $GITHUB_OUTPUT
          else
            echo "merge_conflict=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate and post explanation if conflict
        if: steps.merge_check.outputs.merge_conflict == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          echo "🔎 Getting PR diff..."
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...HEAD | head -c 8000)

          echo "📨 Sending to OpenAI..."
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"model\":\"gpt-4\",\"messages\":[{\"role\":\"user\",\"content\":\"Here is a GitHub pull request diff:\n\n$DIFF\n\nExplain what this PR does, what was changed, and why. Summarize in plain English for developers.\"}],\"temperature\":0.5}")

          COMMENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          echo "💬 Posting AI comment to PR..."
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\":\"### 🤖 PR Summary by AI:\n$COMMENT\"}"
