      - name: Generate and post explanation if conflict
        if: steps.merge_check.outputs.merge_conflict == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          echo "🔎 Getting PR diff..."
          DIFF=$(git diff origin/${{ github.event.pull_request.base.ref }}...HEAD | head -c 8000)

          echo "📨 Sending to OpenAI..."
          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
{
  "model": "gpt-4",
  "messages": [
    {
      "role": "user",
      "content": "Here is a GitHub pull request diff:\n\n$DIFF\n\nExplain what this PR does, what was changed, and why. Summarize in plain English for developers."
    }
  ],
  "temperature": 0.5
}
EOF
          )

          COMMENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

          echo "💬 Posting AI comment to PR..."
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "$(jq -nc --arg body "### 🤖 PR Summary by AI:\n$COMMENT" '{body: $body}')"
